# konfigurasi pre commit
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-executables-have-shebangs
          - id: check-yaml

    # pre commit dari prettier
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "v4.0.0-alpha.8"
      hooks:
          - id: prettier
            additional_dependencies:
                - prettier@^3.2.2

    # pre commit dari eslint
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: "v8.56.0"
      hooks:
          - id: eslint
            files: \.[jt]sx?$
            types: [file]

    # pre commit dari markdownlint
    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.39.0
      hooks:
          - id: markdownlint
