name: Pull Request Build

on:
    pull_request:
        branches:
            - develop
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Build Next.js
              run: |
                  bun install --frozen-lockfile
                  bun lint
                  bun run build

            - name: Check Build Status
              run: |
                  if [ $? -eq 0 ]; then
                    echo "Build successful"
                  else
                    echo "Build failed. Exiting..."
                    exit 1
                  fi

            - name: Comment on Pull Request (on failure)
              if: failure()
              env:
                  GH_TOKEN: ${{ secrets.WF_TOKEN }}
                  PR: ${{ github.event.pull_request.html_url }}
              run: |
                  LAST_COMMIT_SHA="${{ github.event.pull_request.head.sha }}"
                  gh pr edit $PR --add-label "invalid"
                  gh pr comment $PR --body "# Building Next.js\nBuild untuk pull request ini tidak berhasil. Sepertinya ada kesalahan dalam kode yang menyebabkan kegagalan build.\nMohon kontributor untuk mengecek kembali kodenya.\n| Last Commit | Status    |\n|-------------|-----------|\n| $LAST_COMMIT_SHA      | Gagal💔    |"

            - name: Comment on Pull Request (on success)
              if: success()
              env:
                  GH_TOKEN: ${{ secrets.WF_TOKEN }}
                  PR: ${{ github.event.pull_request.html_url }}
              run: |
                  LAST_COMMIT_SHA="${{ github.event.pull_request.head.sha }}"
                  gh pr edit $PR --add-label "invalid"
                  gh pr comment $PR --body "# Building Next.js\nBuild untuk pull request ini berhasil!🎉. Mohon untuk menunggu para Maintainer mereview kodemu!.\n| Last Commit | Status    |\n|-------------|-----------|\n| $LAST_COMMIT_SHA      | Berhasil🩵    |"
